/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package linketinder

import linketinder.View.Menu

class App {

    static void main(String[] args) {
        Menu.start()
    }
}
